apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lurus-newapi-pdb
  namespace: lurus-system
  labels:
    app: lurus-newapi
    app.kubernetes.io/name: lurus-newapi
    app.kubernetes.io/part-of: lurus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: lurus-newapi
